# Generated by Django 5.2.4 on 2025-08-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AadhaarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aadhaar_images/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=14, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('extracted_on', models.DateTimeField(auto_now_add=True)),
                ('extraction_successful', models.BooleanField(default=False)),
                ('raw_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
