# Generated by Django 5.2.4 on 2025-08-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhaardata',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aadhaardata',
            name='back_extraction_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aadhaardata',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar_back_images/'),
        ),
        migrations.AddField(
            model_name='aadhaardata',
            name='back_raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
