# Generated by Django 5.2.4 on 2025-08-05 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor_app', '0002_aadhaardata_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadhaarBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_image', models.ImageField(upload_to='aadhaar_back_images/')),
                ('address', models.TextField(blank=True, null=True)),
                ('extracted_on', models.DateTimeField(auto_now_add=True)),
                ('extraction_successful', models.BooleanField(default=False)),
                ('raw_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AadhaarFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aadhaar_front_images/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=14, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('extracted_on', models.DateTimeField(auto_now_add=True)),
                ('extraction_successful', models.BooleanField(default=False)),
                ('raw_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AadhaarData',
        ),
        migrations.AddField(
            model_name='aadhaarback',
            name='front_card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='back_side', to='extractor_app.aadhaarfront'),
        ),
    ]
